Split roles for cli & server (#21)
* Split the cli & server playbooks & roles

diff --git a/install/qpc-tools b/install/qpc-tools
--- a/install/qpc-tools
+++ b/install/qpc-tools
@@ -14,9 +14,11 @@
 export PATH=$PATH:$ANSIBLE_HOME/bin
 #Note: The playbook path will be sed replaced in the spec file
 # to match the location of where the package is being installed.
-PLAYBOOKFILE="qpc_playbook.yml"
+CLI_PLAYBOOK_FILE="cli_playbook.yml"
+SERVER_PLAYBOOK_FILE="server_playbook.yml"
 PLAYBOOKPATH=""
-PLAYBOOK=$PLAYBOOKPATH$PLAYBOOKFILE
+CLI_PLAYBOOK=$PLAYBOOKPATH$CLI_PLAYBOOK_FILE
+SERVER_PLAYBOOK=$PLAYBOOKPATH$SERVER_PLAYBOOK_FILE
 QPC_TOOLS_VERSION='BUILD_VERSION_PLACEHOLDER'
 
 config_usage() {
@@ -99,26 +101,40 @@ EOM
     exit 0
 }
 
-install() {
+install_cli() {
 shift
 # shift removes the $1 in the positional args
 if [[ $EUID -ne 0 ]]
 then
-  echo ansible-playbook $PLAYBOOK -vv -K $*
-  ansible-playbook $PLAYBOOK -vv -K $*
+  echo ansible-playbook cli/$CLI_PLAYBOOK -vv -K $*
+  ansible-playbook cli/$CLI_PLAYBOOK -vv -K $*
 else
-  echo ansible-playbook $PLAYBOOK -vv $@
-  ansible-playbook $PLAYBOOK -vv $*
+  echo ansible-playbook cli/$CLI_PLAYBOOK -vv $*
+  ansible-playbook cli/$CLI_PLAYBOOK -vv $*
 fi
-
-unset args
 if [ $? -eq 0 ]
 then
-  echo "Installation complete."
-  exit 0
+  echo "CLI installation complete."
 else
-  echo "Installation failed. Review the install logs."
-  exit 1
+  echo "CLI installation failed. Review the install logs."
+fi
+}
+
+install_server() {
+shift
+if [[ $EUID -ne 0 ]]
+then
+  echo ansible-playbook server/$SERVER_PLAYBOOK -vv -K $*
+  ansible-playbook server/$SERVER_PLAYBOOK -vv -K $*
+else
+  echo ansible-playbook server/$SERVER_PLAYBOOK -vv $*
+  ansible-playbook server/$SERVER_PLAYBOOK -vv $*
+fi
+if [ $? -eq 0 ]
+then
+  echo "Quipucords server installation complete."
+else
+  echo "Quipucords server installation failed. Review the install logs."
 fi
 }
 
@@ -130,7 +146,8 @@ then
   fi
   # pass the positional args for the script
   # to the function to prevent scoping issues.
-  install $*;
+  install_server $*;
+  install_cli $*;
 else
 config_usage;
 fi
